import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#FBF5F7',
  '--slot4-page-text': '#1A0A2E',
  '--slot4-panel-bg': '#F3E8FF',
  '--slot4-surface-bg': '#FFFFFF',
  '--slot4-muted-text': '#7A6B99',
  '--slot4-soft-muted-text': '#B8A9D4',
  '--slot4-accent': '#B331F1',
  '--slot4-accent-fill': '#B331F1',
  '--slot4-accent-soft': '#F3E8FF',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1A0A2E',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#EEE5FF',
  '--slot4-cream': '#FBF5A7',
  '--slot4-warm': '#FFF0F8',
  '--slot4-lavender': '#F3E8FF',
  '--slot4-gray': '#F8F5FF',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#FBF5F7',
  '--editable-page-text': '#1A0A2E',
  '--editable-container': '1280px',
  '--editable-border': '#EEE5FF',
  '--editable-nav-bg': '#1A0A2E',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#B331F1',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#B331F1',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#1A0A2E',
  '--editable-footer-text': '#E8D5FF',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_4px_rgba(179,49,241,0.06)]',
  shadowStrong: 'shadow-[0_8px_32px_rgba(179,49,241,0.14)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(26,10,46,0.02),rgba(26,10,46,0.80))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-bold uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-extrabold leading-[1.05] tracking-[-0.03em] sm:text-5xl lg:text-7xl',
    sectionTitle: 'text-3xl font-extrabold tracking-[-0.02em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_8px_32px_rgba(179,49,241,0.16)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
